### ISSUE TITLE
DUDEE - Remove your email and password from the code. 

### ISSUE THREAD

**Issue by markdevjapan** [Dankh917/Instagram-bot#1]
DUDEE - Remove your gmail email and password from the code, as it says in the title.

**Comment by Dankh917** [comment]
hey markdev thank you for noticing me I already did it , got a nofication from g-mail saying someone tried to log in from some district in japan I gues it was you . any way thank you :)

**Comment by markdevjapan** [comment]
Nope not me.. I just happened to be looking for Instagram bots.. if it was me, and if I was a bad enough person, I would have brute forced every social media and account online with those credentials. 

There are bots that look for keywords and phrases... so... don't make that mistake again. :) 

Use gitignore for files you don't wanna upload and always use .env files with this method for passwords etc....

**Comment by Dankh917** [comment]
hey Mark im kind of new to git so thank you very much man...


‫בתאריך יום ב׳, 12 באוק׳ 2020 ב-12:03 מאת ‪Mark Petherbridge‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Dankh917** [comment]
hey mark kind of new to git and dont use it a lot , thank you very much man !

**Comment by Dankh917** [comment]
> Use gitignore for files you don't wanna upload and always use .env files with this method for passwords etc....
will do next time

**Comment by markdevjapan** [comment]
No worries. We all learn sometime and I dare say there are probably huge things I forget and don't know :) a mistake isn't a problem unless you don't learn from it. :) 

Happy coding bro :)

**Comment by Dankh917** [comment]
thank you very much , you too
